### ISSUE TITLE
Add ML programs

### ISSUE THREAD

**Issue by ravish0007** [fsmk/CS-VTU-Lab-Manual#168]
During my study, I was frustrated with not so understandable ML lab programs, so I created these just a day before final LAB exam to prepare myself and to help my friends.

May I raise a PR to push these into this repo? 
https://github.com/ravish0007/ml

**Comment by shijiltv** [comment]
This repository is not maintained. We need to add some notes on README regarding this

Feel free to contribute here  https://gitlab.com/lab_manuals. We are planning to promote this repository going forward. At present @prabodhcp  maintain the gitlab lab manuals.

**Comment by ravish0007** [comment]
Will raise a merge request there, Thank you.
