### ISSUE TITLE
Need to add contributors list to the repo

### ISSUE THREAD

**Issue by viggyprabhu** [fsmk/CS-VTU-Lab-Manual#96]
We need to start maintaining all the list of students who have contributed to the repository. Also need to understand how we will manage the names and put it in the Lab Manual once it becomes a big list.

**Comment by KarthikNayak** [comment]
@viggyprabhu has this been done? assigning the issue to you.

**Comment by viggyprabhu** [comment]
Yes, this was done. However new contributors who have contributed on github are not added. Will raise a separate issue to discuss how to discuss where to add list of contributors, in manual or move it to the website.
